site_name: Yuanji's Wiki
repo_url: https://github.com/masakichi/wiki
edit_uri: edit/main/docs/
nav:
  - Introduction: index.md
  - Coding:
      - coding/git.md
      - coding/markdown.md
      - coding/python.md
      - coding/frontend.md
      - coding/vim.md
  - DevOps:
      - devops/ansible.md
      - devops/jenkins.md
  - Sysadmin:
      - sysadmin/archlinux.md
      - sysadmin/android.md
      - sysadmin/providers.md
      - sysadmin/installation.md
      - sysadmin/code-server.md
      - sysadmin/postgresql.md
      - sysadmin/acme.sh.md
      - sysadmin/services.md
      - sysadmin/wireguard.md
  - Toolkit: toolkit.md
  - Life:
      - life/camera.md
      - life/recipe.md
  - Blog: https://blog.gimo.me
theme:
  font:
    text: Cantarell
    code: Inconsolata
  name: material
  #custom_dir: overrides
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    - navigation.indexes
    - navigation.instant
    #- navigation.sections
    - navigation.expand
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - mdx_truly_sane_lists:
      nested_indent: 2
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
